# Uncomment this line to define a global platform for your project
# platform :ios, "7.0"
platform :ios, "13.0"
use_frameworks!

target "GitHubList" do
    pod "Alamofire"
    pod "AlamofireImage"
end